### ISSUE TITLE
serve directory from node server

### ISSUE THREAD

**Issue by ansuz** [drsn0w/cjdns-web#5]
Planning to do this tonight.

**Comment by drsn0w** [comment]
If possible can this implement htaccess? That would avoid the necessity for a PhD auth system

**Comment by ansuz** [comment]
what files were you hoping to restrict?

There are a couple options for authorization if you want to restrict access to administering your node

* password auth
  + this is total crap
* IPV6 auth
  + this is only good if the authorized node doesn't share its address with anyone (proxies can't use this system)
* some combination of the two options listed above
  + you need the correct host AND a password. More secure but less convenient
* [ssh auth](https://medium.com/@shazow/ssh-how-does-it-even-9e43586e4ffc)

IPv6 auth is really easy to implement. Password auth has a million examples. SSH auth for HTTP would take research, but that comes with the territory of trying to build new, useful tools.

**Comment by ansuz** [comment]
in any case, we probably want to make it configurable.

**Comment by drsn0w** [comment]
IPv6 auth would be through CJDNS then? I was thinking this could be used to administer it through the v4 clearnet as well, for initial setup, if all your peers go down, etc


Sent by Outlook for Android





On Tue, Sep 15, 2015 at 11:10 AM -0700, "ansuz" <notifications@github.com> wrote:
in any case, we probably want to make it configurable.

---

**Comment by ansuz** [comment]
If you're hoping to put it on clearnet, then we probably want to implement some kind of two factor authentication. Security is srs business.

**Comment by drsn0w** [comment]
SSH auth looks interesting, how would we implement that for Web though?

**Comment by drsn0w** [comment]
Moved to #6

**Comment by ansuz** [comment]
exactly. It's new and non-trivial. That would be a new repo, and technically not a 'web' interface unless you want to implement an ssh browser.

**Comment by drsn0w** [comment]
What's wrong with a username/password pair authentication? Enforcing strict password strength requirements of course

**Comment by ansuz** [comment]
re: [enforcing passwords](https://www.youtube.com/watch?v=luv_bWmb9lE&feature=youtu.be)

it's not too hard to brute force a password. That's fine for your myspace account, but administering a node could open you up to abuse that could cost you money (adding peers and abusing your bandwidth).

**Comment by drsn0w** [comment]
We can worry about the auth later, we can probably wrap it around the existing stuff...for now it could be restricted to running on localhost

**Comment by ansuz** [comment]
yea, I'd suggest only binding to a local address or an ipv6. It doesn't need to be _restricted_, but we'd definitely want to document the risks.

**Comment by drsn0w** [comment]
Let the user make their own choices but yell at them for bad one.  I love it :D

**Comment by ansuz** [comment]
[fixed](https://github.com/drsn0w/cjdns-web/commit/e050570332386cb40c3b0ced27dc5b4ab242eff9)
