### ISSUE TITLE
Authentication system

### ISSUE THREAD

**Issue by drsn0w** [drsn0w/cjdns-web#6]
Need a secure authentication system to prevent unauthorised access to administration

**Comment by drsn0w** [comment]
Closed as irrelevant

**Comment by ansuz** [comment]
back in my day issues stayed open til they were implemented.

**Comment by drsn0w** [comment]
we're not going to iplement it D:

**Comment by ansuz** [comment]
isn't a cjdns ipv6 based auth system still an auth system? are we not going to implement that?

**Comment by drsn0w** [comment]
Right


Sent by Outlook for Android





On Sat, Sep 19, 2015 at 11:44 AM -0700, "ansuz" <notifications@github.com> wrote:
isn't a cjdns ipv6 based auth system still an auth system? are we not going to implement that?

---
